// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRaQtdiMvJPxHZvZo8JIjpdlZjaUZF4HE',
    appId: '1:127970826239:web:b87a562b9942517a6279ca',
    messagingSenderId: '127970826239',
    projectId: 'love-soda-flutter',
    authDomain: 'love-soda-flutter.firebaseapp.com',
    databaseURL: 'https://love-soda-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'love-soda-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVwg4eWoWB2TwrGGEwKTyxHXwG8yZ78uY',
    appId: '1:127970826239:android:8c0439acd3a74a746279ca',
    messagingSenderId: '127970826239',
    projectId: 'love-soda-flutter',
    databaseURL: 'https://love-soda-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'love-soda-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgM_ttBBJlul52-RzBT8rbqMnqm5XrNsQ',
    appId: '1:127970826239:ios:f9f99bc7e72edeea6279ca',
    messagingSenderId: '127970826239',
    projectId: 'love-soda-flutter',
    databaseURL: 'https://love-soda-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'love-soda-flutter.appspot.com',
    iosClientId: '127970826239-rlai02sa42mrvbro09odvo9rc4ti6qmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.daisy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgM_ttBBJlul52-RzBT8rbqMnqm5XrNsQ',
    appId: '1:127970826239:ios:f9f99bc7e72edeea6279ca',
    messagingSenderId: '127970826239',
    projectId: 'love-soda-flutter',
    databaseURL: 'https://love-soda-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'love-soda-flutter.appspot.com',
    iosClientId: '127970826239-rlai02sa42mrvbro09odvo9rc4ti6qmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.daisy',
  );
}
